"""Rename promotion_id

Revision ID: 2a703462039d
Revises: 98a394ac980f
Create Date: 2025-07-06 16:06:49.044705

"""
from typing import Sequence, Union
import sqlmodel 
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a703462039d'
down_revision: Union[str, Sequence[str], None] = '98a394ac980f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('shop_item_id', sa.Integer(), nullable=True))
    #op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.drop_column('item', 'promotion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('promotion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_column('item', 'shop_item_id')
    # ### end Alembic commands ###
