"""add limit and cooldown

Revision ID: bbc4a12e65cb
Revises: 2a703462039d
Create Date: 2025-07-07 13:08:41.044722

"""
from typing import Sequence, Union
import sqlmodel 
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc4a12e65cb'
down_revision: Union[str, Sequence[str], None] = '2a703462039d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('use_limit', sa.Integer(), nullable=False))
    op.add_column('item', sa.Column('cooldown', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'cooldown')
    op.drop_column('item', 'use_limit')
    # ### end Alembic commands ###
