"""cascade

Revision ID: e53685e20ec0
Revises: e5a4bc901b60
Create Date: 2025-06-28 11:00:34.642862

"""
from typing import Sequence, Union
import sqlmodel 
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53685e20ec0'
down_revision: Union[str, Sequence[str], None] = 'e5a4bc901b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inventoryitem_item_id_fkey'), 'inventoryitem', type_='foreignkey')
    op.drop_constraint(op.f('inventoryitem_inventory_id_fkey'), 'inventoryitem', type_='foreignkey')
    op.create_foreign_key(None, 'inventoryitem', 'inventory', ['inventory_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'inventoryitem', 'item', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventoryitem', type_='foreignkey')
    op.drop_constraint(None, 'inventoryitem', type_='foreignkey')
    op.create_foreign_key(op.f('inventoryitem_inventory_id_fkey'), 'inventoryitem', 'inventory', ['inventory_id'], ['id'])
    op.create_foreign_key(op.f('inventoryitem_item_id_fkey'), 'inventoryitem', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###
