name: inventory
services:

  postgresdb:
    image: postgres:16-alpine
    container_name: db-inventory
    restart: always
    mem_limit: 1G
    ports:
      - 5432:5432
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ../.data/db:/var/lib/postgresql/data
