FROM python:3.12-slim

# Установка системных зависимостей
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /application

# Копирование и установка основных зависимостей
COPY requirements/requirements.txt .
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

# Копирование и установка тестовых зависимостей
COPY requirements/test-requirements.txt .
RUN pip3 install -r test-requirements.txt

# Копирование кода приложения
COPY app/ ./app
COPY tests/ ./tests
COPY pytest.ini .

# Создание директории для логов
RUN mkdir -p /application/app/logs

# Команда по умолчанию для запуска тестов
CMD ["pytest", "--maxfail=10", "--disable-warnings", "-v"] 